spring.application.name=server
server.port=8080
spring.data.mongodb.uri=mongodb+srv://LmsPaf:lmspaf@lmspaf.gbiahbh.mongodb.net/smart_campus?retryWrites=true&w=majority
spring.mongodb.uri=mongodb+srv://LmsPaf:lmspaf@lmspaf.gbiahbh.mongodb.net/smart_campus?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true
app.jwt.secret=${JWT_SECRET:}
app.jwt.expiration-ms=86400000
app.google.client-id=${GOOGLE_CLIENT_ID:294466105136-raf25i5vlqprte38j711s3g682q98nss.apps.googleusercontent.com}
